#!/bin/bash
#SBATCH --job-name=cellranger
#SBATCH --output=cellranger.out
#SBATCH --error=cellranger.err
#SBATCH --nodes=1
#SBATCH --ntasks=24
#SBATCH --time=72:00:00
#SBATCH --mem=128G

OUTPUT_DIR="/data/ebaird/scRNAseq/SCENTINELsep24/cellranger"
mkdir -p "$OUTPUT_DIR"
cd "$OUTPUT_DIR"

/opt/bin/cellranger-8.0.1/cellranger count --id gal_12d --transcriptome /opt/ref/Drosophila_melanogaster/EnsemblBDGP6.46/dm6_BDGP_46_113_GFP_RFP --sample=2196_2024 --fastqs=/data/vtheodorou/SCENTINEL/SCENTINELSep24_10xGEX.IRB/Fastq_2223TF2NX/2196 --create-bam=true --localcores=40

/opt/bin/cellranger-8.0.1/cellranger count --id flp_10d --transcriptome /opt/ref/Drosophila_melanogaster/EnsemblBDGP6.46/dm6_BDGP_46_113_GFP_RFP --sample=2197_2024 --fastqs=/data/vtheodorou/SCENTINEL/SCENTINELSep24_10xGEX.IRB/Fastq_2223TF2NX/2197 --create-bam=true --localcores=40

/opt/bin/cellranger-8.0.1/cellranger count --id gal_10d --transcriptome /opt/ref/Drosophila_melanogaster/EnsemblBDGP6.46/dm6_BDGP_46_113_GFP_RFP --sample=2198_2024 --fastqs=/data/vtheodorou/SCENTINEL/SCENTINELSep24_10xGEX.IRB/Fastq_2223TF2NX/2198 --create-bam=true --localcores=40

/opt/bin/cellranger-8.0.1/cellranger count --id flp_12d --transcriptome /opt/ref/Drosophila_melanogaster/EnsemblBDGP6.46/dm6_BDGP_46_113_GFP_RFP --sample=2199_2024 --fastqs=/data/vtheodorou/SCENTINEL/SCENTINELSep24_10xGEX.IRB/Fastq_2223TF2NX/2199 --create-bam=true --localcores=40
